name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      run: echo "pass"

    - name: Rust Caching
      run: echo "pass"

    - name: Install toolchain
      run: echo "pass"

    # Using thumbv6m-none-eabi as ARMv6-M arbitrary common choice for a bare-minimum target.
    # More info: https://docs.rs/cortex-m-rt/latest/cortex_m_rt/
    #
    # Can be replaced by other targets that guarantee bare-minimum no-std
    - name: Install toolchain no-std
      run: echo "pass"

    - name: Install Cargo.toml linter
      run: echo "pass"

    - name: Run Cargo.toml linter
      run: echo "pass"

    - name: Install rustfmt
      run: echo "pass"

    - name: Check formatting
      run: echo "pass"

    - name: Install clippy
      run: echo "pass"

    - name: Clippy
      run: echo "pass"

    - name: Build
      run: echo "pass"

    - name: Build no-std
      run: echo "pass"

    - name: Build no-std serde
      run: echo "pass"

    - name: Run tests
      run: echo "pass"

    - name: Run tests no-std
      run: echo "pass"

    - name: Run serde tests
      run: echo "pass"

    - name: Run serde tests no-std
      run: echo "pass"
